# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github

      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'ro.gs1.quarkus-etcd-client'
          ignore-versions: '^[v\d.]+(?!-SNAPSHOT)$'
          min-versions-to-keep: 0

      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'ro.gs1.quarkus-etcd-client-parent'
          ignore-versions: '^[v\d.]+(?!-SNAPSHOT)$'
          min-versions-to-keep: 0

      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'ro.gs1.quarkus-etcd-client-deployment'
          ignore-versions: '^[v\d.]+(?!-SNAPSHOT)$'
          min-versions-to-keep: 0

      - name: Build with Maven
        run: mvn -B package --file pom.xml -q
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -Dmaven.test.skip=true -q
        env:
          GITHUB_TOKEN: ${{ github.token }}