name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to checkout when cutting the release."
        required: true
        default: "master"
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"

jobs:
  release:
    runs-on: ubuntu-latest
    name: release

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml # location for the settings.xml file

      - name: Configure Git author
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Maven release
        run: |
          git checkout -b release-${{ github.event.inputs.releaseVersion }}
          git fetch --tags
          gpg --list-keys
          mvn -B release:prepare -Prelease -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }} -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml
          git checkout ${{ github.base_ref }}
          git rebase release-${{ github.event.inputs.releaseVersion }}
          mvn -B release:perform -Darguments=-DperformRelease -DperformRelease -Prelease -Pgithub -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Push changes to ${{ github.base_ref }}
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{github.base_ref}}

      - name: Push tags
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          branch: ${{github.base_ref}}
